on:
  push:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew 
          ./gradlew bootJar

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Image Build and Push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SECRET_KEY }}
          script: |
            cd /home/ubuntu/

            sudo mkdir -p ./src/main/resources
            sudo touch ./src/main/resources/application.yml
            echo "${{ secrets.APPLICATION }}" | sudo tee ./src/main/resources/application.yml > /dev/null
            cat ./src/main/resources/application.yml

            sudo touch ./docker-compose.yml
            echo "${{ secrets.DOCKER_COMPOSE }}" | sudo tee ./docker-compose.yml > /dev/null

            sudo chmod 666 /var/run/docker.sock
            sudo docker ps -qa | xargs -r sudo docker rm -f
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE }}
            docker-compose -f ./docker-compose.yml --env-file ./src/main/resources/application.yml up -d
            docker image prune -f
